#!/bin/sh

# ensure that multiple, simultaneous IOCs are not started by this user ID

MY_UID=`id -u`
IOC_PID="`/usr/bin/pgrep raspi\$ -u ${MY_UID}`"

if [ "" != "${IOC_PID}" ] ; then
  echo "raspi IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi


export PV_PREFIX=`hostname`:

# see: https://unix.stackexchange.com/questions/119269/how-to-get-ip-address-using-shell-script#119272
export IP_ADDR=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d'/'`

# start the IOC
sudo -E ../../bin/${EPICS_HOST_ARCH}/raspi st.cmd
